spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

external-service:
  auth-service-url: http://localhost:8889/auth
server:
  port: 8080